version: 3.0.0

variables:
  - name: AbstractEnv_DIR
    type: path
    value: SharedResources/ApplicationModels/TestEnvironmentControl

system-variables:
  - file-path: ./SharedResources/SysVars/TestEnvironment.vsysvar

datasources:
  - file-path: ./SharedResources/ApplicationModels/FanModel/Fan.vcdl
  - file-path: ${AbstractEnv_DIR}/TestEnvironmentAbstraction.vcdl

application-models:
  - file-path: ./SharedResources/ApplicationModels/FanModel/Fan.can
  - file-path: ${AbstractEnv_DIR}/TestEnvironmentControl.can